language: node_js
node_js:
- stable
before_install:
- rvm install 2.2.2
- openssl aes-256-cbc -K $encrypted_ea7e43e961c0_key -iv $encrypted_ea7e43e961c0_iv -in travis_rsa.enc -out travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
script: gulp travis
deploy:
  script: .travis/deploy.sh


