branches:
  #whitelist
  only:
    - development
    #- /^deploy-.*$/ # regex ok
  #blacklist
  except:
    #- dontrunme
    #- test

language: node_js
node_js:
  - "stable"

env:
  global:
    - PACKAGE_FILE_NAME=package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.tgz
    - DEPLOY_REMOTE_BUILD_FOLDER=b-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID
    - INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME=install.sh
    - DEPLOY_REMOTE_FOLDER=/home/node/kolafun/
    - BUILD_FOLDER_PREFIX=b
    - SITE_WEB_FOLDER=web
    - SITE_NAME=dev.kolafun.appiume.com
    - SITE_SCRIPT_BOOTSTRAP=$DEPLOY_REMOTE_FOLDER$BUILD_FOLDER_PREFIX-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID/$SITE_WEB_FOLDER/server.js
    - SH_SCRIPT_FILE_NAME=$DEPLOY_REMOTE_BUILD_FOLDER/$INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME

addons:
  ssh_known_hosts: 139.59.36.122

before_install:
  #
  - sudo apt-get -qq update
  - sudo apt-get install ruby-dev

install:
  #
  - npm install

before_script:
  #

script: gulp travis1

after_success:
  #
  - tar -czvf $PACKAGE_FILE_NAME . --exclude=gulpfile.js --exclude=deploy_rsa.enc --exclude=.gitignore --exclude=.git --exclude=$PACKAGE_FILE_NAME
  - mkdir $DEPLOY_REMOTE_BUILD_FOLDER
  - mv $PACKAGE_FILE_NAME $DEPLOY_REMOTE_BUILD_FOLDER
  - echo "#!/bin/sh" >> $SH_SCRIPT_FILE_NAME
  - echo "cd $DEPLOY_REMOTE_FOLDER$DEPLOY_REMOTE_BUILD_FOLDER" >> $SH_SCRIPT_FILE_NAME
  - echo "mkdir web" >> $SH_SCRIPT_FILE_NAME
  #extract
  - echo "tar -xf $PACKAGE_FILE_NAME -C web" >> $SH_SCRIPT_FILE_NAME
  #pm2
  - echo "pm2 stop $SITE_NAME" >> $SH_SCRIPT_FILE_NAME
  - echo "pm2 delete $SITE_NAME" >> $SH_SCRIPT_FILE_NAME
  - echo "pm2 start $SITE_SCRIPT_BOOTSTRAP --name $SITE_NAME" >> $SH_SCRIPT_FILE_NAME

  - echo "#$DEPLOY_REMOTE_FOLDER$SH_SCRIPT_FILE_NAME" >> $SH_SCRIPT_FILE_NAME
  - chmod +x $SH_SCRIPT_FILE_NAME

before_deploy:
  #
- openssl aes-256-cbc -K $encrypted_32a7a5230582_key -iv $encrypted_32a7a5230582_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: false
  script:
    - scp -r $TRAVIS_BUILD_DIR/$DEPLOY_REMOTE_BUILD_FOLDER root@139.59.36.122:$DEPLOY_REMOTE_FOLDER
    
after_deploy:
  #
  ssh root@139.59.36.122 "$DEPLOY_REMOTE_FOLDER$DEPLOY_REMOTE_BUILD_FOLDER/$INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME"
