language: node_js
node_js:
  - "stable"

addons:
  ssh_known_hosts: 139.59.36.122

before_install:
  #

install:
  #

before_script:
  - npm install

script: gulp travis

before_deploy:
- openssl aes-256-cbc -K $encrypted_32a7a5230582_key -iv $encrypted_32a7a5230582_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR root@139.59.36.122:/home/node/kolofun/$TRAVIS_BUILD_ID
  on:
    branch: master
