language: node_js
node_js:
  - "stable"

addons:
  ssh_known_hosts: 139.59.36.122

before_install:
  #
  - sudo apt-get -qq update
  - sudo apt-get install ruby-dev

install:
  #
  - npm install

before_script:

script: gulp travis1

after_success:
  #
  - mkdir build
  - mv * build
  - tar -czf package-build-$TRAVIS_BUILD_ID.tgz build

before_deploy:
- openssl aes-256-cbc -K $encrypted_32a7a5230582_key -iv $encrypted_32a7a5230582_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
#- sshpass -e ssh root@139.59.36.122 <path_to_sh_file>

deploy:
  provider: script
  skip_cleanup: true
  script:    
    - scp -r $TRAVIS_BUILD_DIR/package-build-$TRAVIS_BUILD_ID.tgz root@139.59.36.122:/home/node/kolofun/
  on:
    branch: master
