language: node_js
node_js:
  - "stable"

addons:
  ssh_known_hosts: 139.59.36.122

before_install:
  #
  - sudo apt-get -qq update
  - sudo apt-get install ruby-dev

install:
  #
  - npm install

before_script:

script: gulp travis1

after_success:
  #
  - mkdir build
  - cp * build
  - tar -czf package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.tgz build/*
  - echo "mkdir b-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID" >> install-package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID
  - echo "tar -xf package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.tgz -C b-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID" >> install-package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.sh

before_deploy:
- openssl aes-256-cbc -K $encrypted_32a7a5230582_key -iv $encrypted_32a7a5230582_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
    - scp -r $TRAVIS_BUILD_DIR/package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.tgz root@139.59.36.122:/home/node/kolafun/
    - scp $TRAVIS_BUILD_DIR/install-package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.sh root@139.59.36.122:/home/node/kolafun/
    #- sshpass -e ssh root@139.59.36.122 /home/node/kolafun/install-package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.sh
  on:
    branch: master
