language: node_js
node_js:
  - "stable"

env:
  global:
    - PACKAGE_FILE_NAME=package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.tgz
    - DEPLOY_REMOTE_BUILD_FOLDER=b-$TRAVIS_BRANCH-$TRAVIS_BUILD_ID
    - INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME=install-package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.sh
    - DEPLOY_REMOTE_FOLDER=/home/node/kolafun/

addons:
  ssh_known_hosts: 139.59.36.122

before_install:
  #
  - sudo apt-get -qq update
  - sudo apt-get install ruby-dev

install:
  #
  - npm install

before_script:

script: gulp travis1

after_success:
  #
  - mkdir build
  - cp * build
  - tar -czf $PACKAGE_FILE_NAME build/*
  - echo "mkdir $DEPLOY_REMOTE_BUILD_FOLDER" >> $INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME
  - echo "tar -xf $PACKAGE_FILE_NAME -C $DEPLOY_REMOTE_BUILD_FOLDER" >> $INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME

before_deploy:
- openssl aes-256-cbc -K $encrypted_32a7a5230582_key -iv $encrypted_32a7a5230582_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
    - echo "Deploying $PACKAGE_FILE_NAME package..."
    - scp -r $TRAVIS_BUILD_DIR/$PACKAGE_FILE_NAME root@139.59.36.122:$DEPLOY_REMOTE_FOLDER
    - echo "Deployed package."
    - echo "Deploying install $INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME script..."
    - scp $TRAVIS_BUILD_DIR/$INSTALL_REMOTE_SSH_SCRIPT_FILE_NAME root@139.59.36.122:$DEPLOY_REMOTE_FOLDER
    - echo "Deployed install script."
    #- sshpass -e ssh root@139.59.36.122 /home/node/kolafun/install-package-$TRAVIS_BRANCH-build-$TRAVIS_BUILD_ID.sh
  on:
    branch: master
